wandb_version: 1

env_name:
  desc: null
  value: TwoRoomEnv
learner:
  desc: null
  value: PPO
project_name:
  desc: null
  value: TwoRoomsSingleTask
timesteps:
  desc: null
  value: 1000000
policy_type:
  desc: null
  value: CnnPolicy
cnn:
  desc: null
  value: minigrid
activation:
  desc: null
  value: fta
feat_dim:
  desc: null
  value: 640
stats_window_size:
  desc: null
  value: 10
record_video:
  desc: null
  value: false
render_mode:
  desc: null
  value: rgb_array
lr:
  desc: null
  value: 0.0003
gamma:
  desc: null
  value: 0.99
batch_size:
  desc: null
  value: 96
n_epochs:
  desc: null
  value: 4
n_steps:
  desc: null
  value: 128
n_envs:
  desc: null
  value: 16
learning_starts:
  desc: null
  value: 1000
train_freq:
  desc: null
  value: 1
exploration_final_eps:
  desc: null
  value: 0.1
target_update_interval:
  desc: null
  value: 500
random_hallway:
  desc: null
  value: false
config_file:
  desc: null
  value: config.yaml
run_num:
  desc: null
  value: -1
analyse_rep:
  desc: null
  value: false
use_wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    code_path: code/discovery/experiments/FeatAct_minigrid/run_minigrid.py
    python_version: 3.10.9
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716094642.714279
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 23
      - 35
      4: 3.10.9
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
